### PR TITLE
Add ch 7 and 8 solutions

### PR DESCRIPTION
**Pull request by ckkissane**
Added my solutions for ch 7 and 8 [here](https://github.com/ckkissane/deep_learning_curriculum/tree/master/solutions)

Ch 7 comments: 
* For "Read the ELK report (the first ~30 pages, which frame the problem) and try to come up with a solution of your own that handles all of the counterexamples in the report.", it looks like there are more counterexamples in the report after the first ~30 pages. I assumed you meant "handles all of the counter examples within the first ~30 pages", but I wasn't sure.

Ch 8:
* This chapter was really interesting!

### CODE REVIEW

**Comment by jacobhilton** [comment]
Thanks! Pushed some clean up to the ELK exercise.

**Comment by jacobhilton** [comment]
@ckkissane FYI I just added an alternative exercise to chapter 7: https://github.com/jacobhilton/deep_learning_curriculum/commit/dc3c5aa0010885ea829426539ab3e5b6b2354cd4 . It might be a bit of a challenge, but curious to see what you think if you feel like giving it a shot!

**Comment by ckkissane** [comment]
Nice, I'll check it out!

**Comment by ckkissane** [comment]
@jacobhilton I took a stab at it here: https://github.com/ckkissane/rlhf-shakespeare

In general I thought it was one of the more novel and fun exercises! It was also probably the biggest challenge, and I think it would have been even harder if I didn't already complete chapters 1 & 6. Other comments:

* The data collection process was really painful since my model rarely produced unambiguously happy samples. I cheated by also handpicking lines from the Shakespeare text and labeling those. 
* Your RL tips were really helpful again (especially the adv normalization trick), although I'm curious why you specified a KL of 50 to stop training? In my experience I was able to maximize reward at way lower KL (around 1-3). 
* I also found that my model quickly learned that it could maximize reward by always producing very similar unconditional samples. This makes sense, but I'm curious if you have any ideas to penalize this. (So far I've tried L2 regularization and it didn't help that much)

Overall really enjoyed this one!

**Comment by jacobhilton** [comment]
Nice, thanks for giving this a test drive!

- I had originally guessed you would want a KL of around 10 nats (based on e.g. WebGPT), but it makes sense that you want something lower than this in this toy setting with less data. I went for 50 nats so that you'd get to see some overoptimization, but I will reduce this number.
- The very similar samples are a problem in real-world RLHF too (this is sometimes called "mode collapse"). It's basically the same problem as entropy collapse in standard RL, where the usual solution is to use an entropy bonus. So in theory you could fix this by incorporating a KL penalty (note that an entropy bonus is just a KL penalty from the uniform distribution over actions), but I suspect you'd need lots of rounds of re-training the RM on fresh on-policy data and re-running RL to get this to work really well. In practice the task usually involves producing conditional samples, where mode collapse isn't quite so damaging.

**Comment by jacobhilton** [comment]
Minor updates: https://github.com/jacobhilton/deep_learning_curriculum/commit/c6425f1bbab65019d42cf0335fd28e4df3530f75

**Comment by ckkissane** [comment]
> * The very similar samples are a problem in real-world RLHF too (this is sometimes called "mode collapse"). It's basically the same problem as entropy collapse in standard RL, where the usual solution is to use an entropy bonus. So in theory you could fix this by incorporating a KL penalty (note that an entropy bonus is just a KL penalty from the uniform distribution over actions), but I suspect you'd need lots of rounds of re-training the RM on fresh on-policy data and re-running RL to get this to work really well. In practice the task usually involves producing conditional samples, where mode collapse isn't quite so damaging.

Interesting, thanks!

**Pull request merged**
