### PR TITLE
Add solutions for transformer exercises

### PR DESCRIPTION
**Pull request by ckkissane**
Thanks for creating this curriculum! I think having solutions to reference would significantly tighten feedback loops for those of us who are self-studying.

To jump start this, I created a notebook with my answers to the exercises for 1-Transformers.

### CODE REVIEW

**Comment by jacobhilton** [comment]
Thanks! I appreciate the offer but I think it's best not to add solutions to the repo directly, for a few reasons:
- I don't have the capacity to vet solutions
- It might tempt people to look at solutions too quickly
- It would make the repo less lightweight

I think what I'll do is to create a solutions page and link to https://github.com/ckkissane/deep_learning_curriculum/tree/master/solutions from that if that sounds OK?

Also, I'm curious if you have any feedback on the curriculum so far.

**Comment by ckkissane** [comment]
> I think what I'll do is to create a solutions page and link to https://github.com/ckkissane/deep_learning_curriculum/tree/master/solutions from that if that sounds OK?

Sounds good to me!

> Also, I'm curious if you have any feedback on the curriculum so far.

I'm really enjoying it so far. I like that it seems to jump straight into very relevant material, and I love the emphasis on active learning through the exercises. My only gripe is that it can be a challenge to verify the correctness of my answers. I think I'll try to pair up with a mentor as you suggested in the README.

**Comment by jacobhilton** [comment]
I've pushed a solutions page to master. Feel free to submit a fresh PR to modify the solutions page if you want to add any comments about your solution.

**Comment by jacobhilton** [comment]
Also, I like your fake Shakespeare sample, nice job! I hadn't actually tested that part of the exercise so it's nice to know it works.

**Pull request closed without merging**
